[package]
name = "sshc"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.4.11", features = ["derive"] }
shellexpand = { version = "3.1.0", features = ["tilde"] }
whoami = "1.4.1"
